version: "3.8"
services:
  api:
    container_name: chatwave.api
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Default=Server=db,1433;Database=ChatWave;User Id=sa;Password=Strong_Password;TrustServerCertificate=true
    depends_on:
      - db
    networks:
      - chatwave-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chatwave.db
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Strong_Password"
      ACCEPT_EULA: "Y"
    networks:
      - chatwave-network
    volumes:
      - chatwave_data:/var/opt/mssql

volumes:
  chatwave_data:
    driver: local

networks:
  chatwave-network:
    driver: bridge