version: "3.8"
services:
  api:
    container_name: chatwave.api
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Default=Server=db,1433;Database=ChatWave;User Id=sa;Password=Strong_Password;TrustServerCertificate=true
      - MongoDBSettings__ConnectionString=mongodb://mongo:27017
      - MongoDBSettings__DatabaseName=ChatWaveEventsDB
    depends_on:
      - db
      - mongo
    networks:
      - chatwave-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chatwave.db
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Strong_Password"
      ACCEPT_EULA: "Y"
    networks:
      - chatwave-network
    volumes:
      - chatwave_data:/var/opt/mssql

  mongo:
    image: mongo:6.0
    container_name: chatwave.mongo
    ports:
      - "27018:27017"
    networks:
      - chatwave-network
    volumes:
      - mongo_data:/data/db

volumes:
  chatwave_data:
    driver: local
  mongo_data:
    driver: local

networks:
  chatwave-network:
    driver: bridge